apps/chargen/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from views import *
from chargen.models import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns("",
    url(r"^list/?$", list),
    url(r"^view/(.*)$", view),
    url(r"^printview/(.*)$", printview),
    url(r"^create/?$", create),
    url(r"^delete/(.*)/?$", delete),
    url(r"^stats/(\d*)/?$", statform),
    url(r"^basics/(\d*)/?$", basicsform),
    url(r"^assignstats/(\d*)/(.*?)/?$", assignstats),
    url(r"^classpage/(\d*)/?$", classpage),
    url(r"^Mage/(\d*)/?$", mage),
    url(r"^Thief/(\d*)/?$", thief),
    url(r"^Fighter/(\d*)/?$", fighter),
    url(r"^Cleric/(\d*)/?$", cleric),
    
    url(r'^admin/', include(admin.site.urls)),
    )
    
if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {
        "template": "homepage.html",
    }, name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
    url(r"^profiles/", include("idios.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^cg/", include("chargen.urls")),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

apps/chargen/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

class Character(models.Model):
	"""
	Character model class.
	"""
    name = models.CharField(max_length=255)
    stats = models.ManyToManyField('CharacterStat')
    creation_date = models.DateField(auto_now_add=True)
    modified_date = models.DateField(auto_now=True)
    portrait = models.ImageField(
		upload_to="portraits", null=True, blank=True)
    user = models.ForeignKey(User)
    race = models.ForeignKey('Race')
    posessions = models.ManyToManyField(
		'Posession',null=True, blank=True)
    weapons = models.ManyToManyField('Weapon',null=True, blank=True)
    cls = models.ForeignKey('Cls') #change to ManyToMany later 
                                   #to allow multiclass
    
    step = models.IntegerField(default=1) #where the character is 
                                          #in the creation process.
                                          #Not yet handled by app.
    details = models.OneToOneField('Details',null=True, blank=True)
    
    number_of_spells = models.IntegerField(
		default=1,null=True, blank=True)
    spells = models.ManyToManyField('Spell',null=True, blank=True) 
    hp = models.IntegerField(default=0,null=True, blank=True)
    skills = models.ManyToManyField('CharSkill', null=True)
    armor = models.ManyToManyField('Armor', null=True)
    
    def __unicode__(self):
        return self.name

class Proficiency(models.Model):
	"""
	Not currently in use.
	
	Represents a sort of sub-skill at which characters may be 
	proficient. Generally used for weapons proficencies, e.g. 
	if a character has the "Sword" proficiency he or she has been
	trainined with that particular weapon and can use it without 
	penalty.
	"""
	
    name = models.CharField(max_length=60)
    
    def __unicode__(self):
        return self.name

class Details(models.Model):
	"""
	Miscellaneous personal properties of the character.
	""" 
    alignment = models.CharField(max_length=40)
    height = models.CharField(max_length=40)
    weight = models.CharField(max_length=40)
    hair = models.CharField(max_length=40)
    eyes = models.CharField(max_length=40)
    story = models.TextField(null=True, blank=True)
    
    def __unicode__(self):
        return "Details..."
        
class CharacterStat(models.Model):
	"""
	Properties of one particular Stat on one Character.
	e.g. a Character's STR of 17.
	"""
    name = models.ForeignKey('Stat') #STR, CON, DEX, etc.
    value = models.IntegerField()
    value_suffix = models.IntegerField(null=True, blank=True) 
    #e.g. for STR 18/00
    
    def __unicode__(self):
        return self.name.abbreviation

class Stat(models.Model):
	"""
	A statistic type available to characters. Usually these would be 
	a fixed list of STR, DEX, CHA, CON, INT, WIS but making this a
	class instead of a list allows admins to add house-rule stats to 
	the list, e.g. COM (Comeliness) or LUK (Luck).  
	"""
    name = models.CharField(max_length=35)
    abbreviation = models.CharField(max_length=6)
    ability_modifiers = models.ManyToManyField(
		'AbilityModifier', null=True, blank=True)
    
    def __unicode__(self):
        return self.name
    
class Race(models.Model):
	"""
	A race such as Elf, Dwarf, etc. Race affects a character's stats, 
	and choices for races should be limited by Stat values.
	""" 
    name = models.CharField(max_length=60)
    stat_adjustments = models.ManyToManyField(
		'StatModifier', null=True, blank=True)
    stat_minimums = models.ManyToManyField(
		'StatMinimum', null=True, blank=True)
    stat_maximums = models.ManyToManyField(
		'StatMaximum', null=True, blank=True)
    abilities = models.ManyToManyField(
		'RacialAbility', null=True, blank=True)
    
    def __unicode__(self):
        return self.name

class Spell(models.Model):
	"""
	Represents a magic spell that can be known by a character.
	"""
    name = models.CharField(max_length=60)
    
    def __unicode__(self):
        return self.name
        
class Skill(models.Model):
	"""
	A skill that can be chosen by a character.
	"""
    name = models.CharField(max_length=60)
    initial_value = models.IntegerField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name
        
class CharSkill(models.Model):
	"""
	A particular skill (with score) for a particular character.
	"""
    name = models.CharField(max_length=60)
    value = models.IntegerField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name        
        
class StatModifier(models.Model):
	"""
	Represents an adjustment to be made to a Stat for a certain Race,
	e.g. Elves get +1 to DEX and -1 to CON.
	"""
    name = models.ForeignKey('Stat')
    value = models.IntegerField()
    
class StatMinimum(models.Model):
	"""
	Required minimum for a Stat for a particular Race. E.g. a user 
	can't choose Elf for his Race unless he has a DEX of 10 or more.
	"""
    name = models.ForeignKey('Stat')
    value = models.IntegerField()
    
class StatMaximum(models.Model):
	"""
	Required maximum for a Stat for a particular Race. E.g. a user 
	can't choose Elf if his STR is 18 or higher.
	"""
    name = models.ForeignKey('Stat')
    value = models.IntegerField()
        
class Posession(models.Model):
	"""
	A generic item available to be owned by a Character, e.g. 50' rope.
	"""
    name = models.CharField(max_length=60)
    weight = models.FloatField(null=True, blank=True)
    value = models.FloatField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name
        
class Armor(models.Model):
	"""
	A type of armor available to be worn by a Character. E.g. Chainmail.
	"""
	#TODO: Implement allowed_classes property to limit armor choices to
	#certain classes, e.g. Mages can't choose Plate Armor.
    name = models.CharField(max_length=60)
    weight = models.FloatField(null=True, blank=True)
    value = models.FloatField(null=True, blank=True)
    ac_modifier = models.IntegerField()
    
    def __unicode__(self):
        return self.name

class Weapon(models.Model):
	"""
	A type of weapon available to be owwned by a Character, 
	e.g. Longsword.
	"""
    name = models.CharField(max_length=60)
    weight = models.FloatField(null=True, blank=True)
    value = models.FloatField(null=True, blank=True)
    allowed_classes = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.name

class Cls(models.Model):  
	"""
	A Class is a Character's chosen profession type, e.g. Mage.
	"""
    name = models.CharField(max_length=60)
    abilities = models.ManyToManyField(
		'ClassAbility', null=True, blank=True)
    allowed_races = models.ManyToManyField('Race')
    minimum_stat_values = models.ManyToManyField(
		'StatMaximum', null=True, blank=True)
    maximum_stat_values = models.ManyToManyField(
		'StatMinimum', null=True, blank=True)
    allowed_weapons = models.ManyToManyField(
		'Weapon', null=True, blank=True)
    number_of_proficiencies = models.IntegerField(default=1)
    #level_thresholds = models.ManyToManyField(LevelThreshold)
    
    def __unicode__(self):
        return self.name
    
class RacialAbility(models.Model):
	"""
	A special talent granted by Race, e.g. Dwarves have a special talent 
	for underground navigation.
	"""
    name = models.CharField(max_length=60)
    explanation = models.TextField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name

class ClassAbility(models.Model):
	"""
	A special talent granted by class. E.g. Paladins can heal once 
	per day.
	"""
    name = models.CharField(max_length=60)
    explanation = models.TextField(null=True, blank=True)
    
    def __unicode__(self):
        return self.name
    
class AbilityModifier(models.Model):
	"""
	A bouns or penalty applied to an ability, skill, activity, etc., 
	as determined by the value of a Stat. E.g. high INT grants a bonus 
	to the maximum number of spells a character can concurrently 
	memorize.
	"""
    name = models.CharField(max_length=100)
    abbreviation = models.CharField(max_length=12)
    stat_value = models.IntegerField()
    mod_value = models.CharField(max_length=100, null=True, blank=True)
    
    def __unicode__(self):
        return self.abbreviation + " " + str(self.stat_value)
    

templates/chargen/basic.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}{{ step_number }}: {{ step_description }}{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <h1>{{ step_number }}</h1>
    {% for key, value in stat_values.items %}
    <p>{{ key }} : {{ value }}</p>
    {% empty %}
    <p>Nothin' here</p>
    {% endfor %}
    <p>Notes would go here</p>
{% endblock %}

templates/chargen/basics.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}DnDCG Basic info{% endblock %}

{% block body_class %}{% endblock %}

{% block body %}
	<p>Set up your basic details. All fields are required.</p>
    <form action="/cg/basics/{{char_id}}/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save info" class="btn primary large" />
    </form>
    {{ form_message }}
{% endblock %}

templates/chargen/chargen.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}{{ step_number }}: {{ step_description }}{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <h1>{{ step_number }}</h1>
    <h2>{{ step_description }}</h2>
    <p>{{ step_note }}</p>
    {% for key, value in stat_values.items %}
    <p>{{ key }} : {{ value }}</p>
    {% empty %}
    <p>Nothin' here</p>
    {% endfor %}
    <p>Notes would go here</p>
{% endblock %}

templates/chargen/charview.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}Character List{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <h1>Character View</h1>
    <h2>{{ character.name }}</h2>
    <table>
    <thead>
    <tr>
    <th>Property:</th>
    <th>Value:</th>
    </tr>
    </thead>
    <tbody>
    <tr>
    <td>Name:</td>
    <td>{{ character.name }}</td>
    </tr>
    <tr>
    <td>Race:</td>
    <td>{{ character.race }}</td>
    </tr>
    <tr>
    <td>Hit Points:</td>
    <td>{{ character.hp }}</td>
    </tr>
    <tr>
    <td>Class:</td>
    <td>{{ character.cls }}</td>
    </tr>
    <tr>
    <td>Created:</td>
    <td>{{ character.creation_date }}</td>
    </tr>
    <tr>
    <td>Modified:</td>
    <td>{{ character.modified_date }}</td>
    </tr>
    {% for stat in character.stats.all %}
    <tr>
    <td>{{ stat.name }}</td>
    <td>{{ stat.value }}</td>
    {% for mod in stat.name.ability_modifiers.all %}
    {% if mod.stat_value == stat.value %}
    <td>{{ mod.name }}: {{ mod.mod_value }}</td>
    {% endif %}
    {% endfor %}
    </tr>
    {% endfor %}
    
    {% if character.details != None %}
    <tr>
    <td>Height:</td>
    <td>{{ character.details.height }}</td>
    </tr>
    <tr>
    <td>Weight:</td>
    <td>{{ character.details.weight }}</td>
    </tr>
    <tr>
    <td>Hair:</td>
    <td>{{ character.details.hair }}</td>
    </tr>
    <tr>
    <td>Eyes:</td>
    <td>{{ character.details.eyes }}</td>
    </tr>
    <tr>
    <td>Alignment:</td>
    <td>{{ character.details.alignment }}</td>
    </tr>
    <tr>
    <td>History:</td>
    <td>{{ character.details.story }}</td>
    </tr>
    {% endif %}
    <tr>
    <td>Weapon Proficiencies:</td>
    {% for weapon in character.weapons.all %}
    <td>{{ weapon.name }}</td>
    {% endfor %}
    </tr>
    {% if character.spells.all|length > 0 %}
    <tr>
    <td>Spell Book:</td>
    {% for spell in character.spells.all %}
    <td>{{ spell.name }}</td>
    {% endfor %}
    </tr>
    {% endif %}
    {% if character.skills.all|length > 0 %}
    <tr>
    <td>Skills:</td>
    {% for skill in character.skills.all %}
    <td>{{ skill.name }}: {{skill.value}}</td>
    {% endfor %}
    </tr>
    {% endif %}
    </tbody>
    </table>
    <p>
    <a class="btn primary large" href="/cg/list">List all characters</a> <span style;"width:40px">&nbsp;</span> 
    <a class="btn primary large" href="/cg/printview/{{ character.id }}">Printable view</a> <span style;"width:40px">&nbsp;</span> 
    <a class="btn primary large" href="/cg/delete/{{ character.id }}" onClick="return confirm('Permanently delete this character?')">Delete this character</a>
    
    </p>
    
{% endblock %}

templates/chargen/charviewprint.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% block extra_head %}
<style type="text/css">
body{padding-top:0px;border:2px solid black;min-height:900px;}
div.topbar{display:none;}
div.container{width:100%;}
table{border:2px solid black; margin:0px;}
td{border:1px solid #bbb;font-size:15px;padding:5px;}
ul{margin-top:10px;}
.legal {display:none;}

</style>
{% endblock %}

{% block head_title %}Character Print View{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}

<table>
<tr>
<td>
Name: {{ character.name }}
</td>
<td>
Race: {{ character.race }}
</td>
<td>
Name: {{ character.cls }}
</td>
<td>
Player: {{ character.user }}
</td>
<td>
Created: {{ character.creation_date }}
</td>
</tr>
</table>
<table style="width:75%;float:left;">
{% for stat in character.stats.all %}
<tr>
<td>{{ stat.name }}</td>
<td>{{ stat.value }}</td>
{% for mod in stat.name.ability_modifiers.all %}

{% if mod.stat_value == stat.value %}
<td style="font-size:13px;padding-left:4px;padding-right:4px;">{{ mod.name }}: {{ mod.mod_value }}</td>
{% endif %}
{% endfor %}
{% ifequal stat.name.name "Luck" %}
<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
{% endifequal %}
{% ifequal stat.name.name "Comeliness" %}
<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
{% endifequal %}
{% ifequal stat.name.name "Charisma" %}
<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
{% endifequal %}
{% ifequal stat.name.name "Dexterity" %}
<td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>
{% endifequal %}
{% ifequal stat.name.name "Wisdom" %}
<td>&nbsp;</td><td>&nbsp;</td>
{% endifequal %}
{% ifequal stat.name.name "Constitution" %}
<td>&nbsp;</td>
{% endifequal %}
{% ifequal stat.name.name "Intelligence" %}
<td>&nbsp;</td>
{% endifequal %}
</tr>
{% endfor %}
</table>
<table style="width:25%;float:right;">
<tr>
<td>Height</td>
<td>{{ character.details.height }}</td>
</tr>
<tr>
<td>Weight</td>
<td>{{ character.details.weight }}</td>
</tr>
<tr>
<td>Hair</td>
<td>{{ character.details.hair }}</td>
</tr>
<tr>
<td>Eyes</td>
<td>{{ character.details.eyes }}</td>
</tr>
<tr>
<td>Alignment</td>
<td>{{ character.details.alignment }}</td>
</tr>
</table>
<div><p style="line-height:30px;padding-left:10px;padding-top:10px;margin-left:10px;margin-top:10px;font-size:17px;">&nbsp;&nbsp;Notes:</p></div>
{% if character.skills.all|length > 0 %}
<table>
<tr>
{% for skill in character.skills.all %}
<td>{{ skill.name }}: {{skill.value}}</td>
{% endfor %}
</tr>
</table>
{% endif %}
<table>
<tr>
<td style="width:20%">Weapon Proficiencies:
<ul>
{% for weapon in character.weapons.all %}
<li>{{ weapon.name }}</li>
{% endfor %}
</ul>
</td>
<td style="width:20%">Armor:
<ul>
{% for armor in character.armor.all %}
<li>{{ armor.name }} (AC -{{armor.ac_modifier}})</li>
{% endfor %}
</ul>
</td>
{% if character.spells.all|length > 0 %}
<td style="width:20%">Spell Book:
<ul>
{% for spell in character.spells.all %}
<li>{{ spell.name }}</li>
{% endfor %}
</ul>
</td>
{% endif %}
<td>Combat Notes:</td>
</table>
<table>
<tr style="height:150px;">
<td style="width:33%">
Possessions
</td>
<td style="width:33%">
Experience
</td>
<td style="width:33%">
Treasure
</td>
</tr>
</table>
    
{% endblock %}

templates/chargen/classpage.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% block extra_head %}
<style type="text/css">
label {float:none; font-weight:bold}
li label {font-weight:normal;width:200px;}
li {list-style-type:none}
ul.errorlist {width:150px;}
</style>
{% endblock %}
{% block head_title %}{{character.cls}} Page{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
<h1>{{character.cls}} Page</h1>
{% if form_message != "" %}
<p style="color:red;font-size:17px;">{{form_message}}</p>
{% endif %}
<p>As a {{character.cls}}, your starting hit points are {{character.hp}}.</p>
<p>{{proficiency_message}}</p>
<p>{{skill_message}}</p>
    <form action="/cg/{{character.cls}}/{{character.id}}/" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Next" class="btn primary large" />
    </form>
{% endblock %}

templates/chargen/form.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% block extra_head %}
<style type="text/css" src="{{STATIC_URL}}css/forms.css"></style>
{% endblock %}

{% block head_title %}Create a new character{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <h1>{{ heading }}</h1>
    <form action="create" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Go!"></input>
    </form>
    <p class="note">{{ form_note }}</p>
{% endblock %}

templates/chargen/list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}Character List{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <h1>Character List</h1>
    <h2>Characters for {{user.username}}:</h2>
    <table id="example" class="display">
    <thead>
        <tr>
            <th>Name</th>
            <th>Race</th>
            <th>Class</th>
            <th>Level</th>
            <th>Created</th>
            <th>Modifed</th>
        </tr>
    </thead>    
    <tbody>
    {% for character in user.character_set.all %}
        <tr>
            <td><a href="/cg/view/{{character.id}}">{{character.name}}</a></td>
            <td>{{character.race}}</td>
            <td>{{character.cls}}</td>
            <td>{{character.level}}</td>
            <td>{{character.creation_date}}</td>
            <td>{{character.modified_date}}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

    <p style="clear:both;padding-top:20px;"><a class="btn primary large" href="create">Create a new character</a></p>

{% endblock %}

templates/chargen/stats.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}DnDCG Stat generation{% endblock %}

<style>
	#sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
	#sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
	#sortable li span { position: absolute; margin-left: -1.3em; }
</style>

{% block body_class %}{% endblock %}

{% block body %}
    <p>Determine how to roll your stats, then hit "Roll 'em!"</p>
    <form action="/cg/stats/{{char_id}}/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Roll 'em!" class="btn primary large" />
    </form>
{% endblock %}

templates/chargen/statsort.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% block extra_head %}

<style type="text/css" title="currentStyle">
			@import "/site_media/static/css/sorty.css";
		</style>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
<script>
	$(function() {
		$( "#sortable" ).sortable();
		$( "#sortable" ).disableSelection();
	});
</script>
<script>
    function updateurl()
    {
        var t = "";
        $("#sortable").children().each(function() {
        t = t + $(this).text() + "_"});
        url = "/cg/assignstats/{{character.id}}/" + t; 
        $("#go").attr("href", url);
    }
    </script>
        
    
{% endblock %}

{% block head_title %}Create a new character{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
<h1>Sort your stats</h1>
<p>Drag the numbers up or down to sort the list so that each number is next to the stat to which you wish to assign it. </p>
<p>Tip: it is easiest if you work your way from the top down.</p><p>Check the order carefully before pressing the button to finalize.</p>
<div id="container" style="width:400px">
	<div style="float:left">
        <ul id="sortable">
            {% for val in vals %}
                <li>{{ val }}</li>
            {% endfor %}
        </ul>
    </div>
    <div style="float:left; margin-left:10px;">
        <ul>
            {% for stat in stats %}
            <li>{{stat.name}}</li>
            {% endfor %}
            
            {% for filler in fillers %}
            <li>{{ filler }}</li>
            {% endfor %}
        </ul>
    </div>
    <div style="clear:both;height:20px;">&nbsp;</div>
    <a id="go" href="/cg/assignstats/{{character.id}}/" onClick="updateurl()" class="btn primary large">Use these assignments</a>
 
{% endblock %}



templates/chargen/statsort2.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% block extra_head %}

<style type="text/css" title="currentStyle">
			@import "/site_media/static/css/sorty.css";
		</style>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
<script>
	$(function() {
		$( "#sortable" ).sortable();
		$( "#sortable" ).disableSelection();
	});
</script>
<script>
    function updateurl()
    {
        var t = "";
        $("#sortable").children().each(function() {
        t = t + $(this).text() + "_"});
        url = "/cg/assignstats/{{character.id}}/" + t; 
        $("#go").attr("href", url);
    }
    </script>
        
    
{% endblock %}

{% block head_title %}Create a new character{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
<h1>Sort your stats</h1>
<p>Drag the numbers up or down to sort the list so that each number is next to the stat to which you wish to assign it. </p>
<p>Tip: it is easiest if you work your way from the top down.</p><p>Check the order carefully before pressing the button to finalize.</p>
<form action="/cg/stats/{{char_id}}/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Roll 'em!" class="btn primary large" />
</form>
<div id="container" style="width:400px">
	<div style="float:left">
        <ul id="sortable">
            {% for val in vals %}
                <li>{{ val }}</li>
            {% endfor %}
        </ul>
    </div>
    <div style="float:left; margin-left:10px;">
        <ul>
            {% for stat in stats %}
            <li>{{stat.name}}</li>
            {% endfor %}
            
            {% for filler in fillers %}
            <li>{{ filler }}</li>
            {% endfor %}
        </ul>
    </div>
    <div style="clear:both;height:20px;">&nbsp;</div>
    <a id="go" href="/cg/assignstats/{{character.id}}/" onClick="updateurl()" class="btn primary large">Use these assignments</a>
 
{% endblock %}

